name: optimus
author: valory
version: 0.1.0
description: An optimism liquidity trader service.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: valory/optimus:0.1.0:bafybeida2scmw3qune3n6ru7tuzquuc3mxs2cfivzcncrtlj4ziadv4sqy
number_of_agents: 1
deployment: {}
---
public_id: valory/optimus_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${LOG_DIR:str:/logs}
  params:
    args:
      setup:
        all_participants: ${ALL_PARTICIPANTS:list:[]}
        consensus_threshold: null
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      earliest_block_to_monitor: ${EARLIEST_BLOCK_TO_MONITOR:int:8053690}
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
      termination_sleep: ${TERMINATION_SLEEP:int:900}
      reset_pause_duration: ${RESET_PAUSE_DURATION:int:300}
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:30}
      retry_attempts: 400
      retry_timeout: 3
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      service_id: optimus
      service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
      share_tm_config_on_startup: ${USE_ACN:bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      tenderly_access_key: ${TENDERLY_ACCESS_KEY:str:access_key}
      tenderly_account_slug: ${TENDERLY_ACCOUNT_SLUG:str:account_slug}
      tenderly_project_slug: ${TENDERLY_PROJECT_SLUG:str:project_slug}
      tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:optimism_tm_0:26656}
      service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://optimism.autonolas.tech/}
      multisend_batch_size: ${MULTISEND_BATCH_SIZE:int:5}
      safe_contract_addresses: ${SAFE_CONTRACT_ADDRESSES:str:{"ethereum":"0x0000000000000000000000000000000000000000","base":"0x0000000000000000000000000000000000000000","optimism":"0x0000000000000000000000000000000000000000"}}
      staking_token_contract_address: ${STAKING_TOKEN_CONTRACT_ADDRESS:str:0x88996bbdE7f982D93214881756840cE2c77C4992}
      staking_activity_checker_contract_address: ${STAKING_ACTIVITY_CHECKER_CONTRACT_ADDRESS:str:0x7Fd1F4b764fA41d19fe3f63C85d12bf64d2bbf68}
      staking_threshold_period: ${STAKING_THRESHOLD_PERIOD:int:5}
      store_path: ${STORE_PATH:str:/data/}
      assets_info_filename: ${ASSETS_INFO_FILENAME:str:assets.json}
      pool_info_filename: ${POOL_INFO_FILENAME:str:current_pool.json}
      gas_cost_info_filename: ${GAS_COST_INFO_FILENAME:str:gas_costs.json}
      merkl_fetch_campaigns_args: ${MERKL_FETCH_CAMPAIGNS_ARGS:str:{"url":"https://api.merkl.xyz/v3/campaigns","creator":"","live":"true"}}
      min_swap_amount_threshold: ${MIN_SWAP_AMOUNT_THRESHOLD:int:10}
      max_fee_percentage: ${MAX_FEE_PERCENTAGE:float:0.02}
      max_gas_percentage: ${MAX_GAS_PERCENTAGE:float:0.25}
      balancer_graphql_endpoints: ${BALANCER_GRAPHQL_ENDPOINTS:str:{"optimism":"https://api.studio.thegraph.com/query/75376/balancer-optimism-v2/version/latest","base":"https://api.studio.thegraph.com/query/24660/balancer-base-v2/version/latest"}}
      allowed_chains: ${ALLOWED_CHAINS:list:["optimism","base"]}
  coingecko:
    args:
      token_price_endpoint: ${COINGECKO_TOKEN_PRICE_ENDPOINT:str:https://api.coingecko.com/api/v3/simple/token_price/{asset_platform_id}?contract_addresses={token_address}&vs_currencies=usd}
      coin_price_endpoint: ${COINGECKO_COIN_PRICE_ENDPOINT:str:https://api.coingecko.com/api/v3/simple/price?ids={coin_id}&vs_currencies=usd}
      api_key: ${COINGECKO_API_KEY:str:null}
      requests_per_minute: ${COINGECKO_REQUESTS_PER_MINUTE:int:30}
      credits: ${COINGECKO_CREDITS:int:10000}
      rate_limited_code: ${COINGECKO_RATE_LIMITED_CODE:int:429}
      chain_to_platform_id_mapping: ${COINGECKO_CHAIN_TO_PLATFORM_ID_MAPPING:str:{"optimism":"optimistic-ethereum","base":"base","ethereum":"ethereum"}}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://virtual.mainnet.rpc.tenderly.co/85a9fd10-356e-4526-b1f6-7148366bf227
      chain_id: 1
      poa_chain: false
      default_gas_price_strategy: eip1559
    base:
      address: https://virtual.arbitrum.rpc.tenderly.co/8973f254-1594-4a82-8e26-25a10a01bf46
      chain_id: 8453
      poa_chain: false
      default_gas_price_strategy: eip1559
    optimism:
      address: https://virtual.arbitrum.rpc.tenderly.co/8973f254-1594-4a82-8e26-25a10a01bf46
      chain_id: 10
      poa_chain: false
      default_gas_price_strategy: eip1559
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
