name: main_workflow

on:
  push:
    branches:
      - develop
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lock_check:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Check if dependencies can be locked
        run: uv lock --check
      - name: Install dependencies
        run: uv sync --all-groups -v

  copyright_and_dependencies_check:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.10"]

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tomte[tox,cli]==0.6.5 tox-uv
      - name: Check copyright headers
        run: tox -e copyright-check
      - name: License compatibility check
        run: tox -e liccheck
      - name: Check dependencies
        run: tox -e check-dependencies
      - name: Check third-party package hashes against upstreams
        run: tox -e check-third-party-hashes
      - name: Check doc links
        run: tomte check-doc-links
      - name: Check doc IPFS hashes
        run: tox -e check-doc-hashes

  linter_checks:
    continue-on-error: False
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.10"]

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tomte[tox,cli]==0.6.5 tox-uv

          # Install `mdspell` for spelling checks
          sudo npm install -g markdown-spellcheck

      - name: Security checks
        run: tomte check-security
      - name: Check packages
        run: tox -e check-packages
      - name: Check hash
        run: tox -e check-hash
      - name: Code checks
        run: tomte check-code
      - name: Check spelling
        run: tomte check-spelling
      - name: AbciApp consistency checks
        run: |
          tox -e check-abci-docstrings
          tox -e check-abciapp-specs
          tox -e check-handlers

  scan:
    name: gitleaks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.10.1/gitleaks_8.10.1_linux_x64.tar.gz
          tar -xzf gitleaks_8.10.1_linux_x64.tar.gz
          sudo install gitleaks /usr/bin
          gitleaks detect --report-format json --report-path leak_report --log-opts="HEAD"

  test:
    continue-on-error: False
    needs:
      - lock_check
      - copyright_and_dependencies_check
      - linter_checks
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - if: matrix.os == 'ubuntu-24.04'
        name: Install dependencies (ubuntu-24.04)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox]==0.6.5 tox-uv
          pip install --user --upgrade setuptools

      - if: matrix.os == 'ubuntu-24.04'
        name: Unit tests ubuntu-24.04
        run: tox -e py${{ matrix.python-version }}-linux

      - if: matrix.os == 'macos-15'
        name: Install dependencies (macos-15)
        run: |
          pip install tomte[tox]==0.6.5 tox-uv

      - if: matrix.os == 'macos-15'
        name: Unit tests macos-15
        run: tox -e py${{ matrix.python-version }}-darwin

      - if: matrix.os == 'windows-2025'
        name: Install dependencies (windows-2025)
        run: |
          pip install tomte[tox]==0.6.5 tox-uv

      - if: matrix.os == 'windows-2025'
        name: Unit tests windows-2025
        run: tox -e py${{ matrix.python-version }}-win

  coverage:
    continue-on-error: False
    needs:
      - test
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox]==0.6.5 tox-uv
          pip install --user --upgrade setuptools
      - name: Check coverage
        run: tox -e coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false

  e2e-tests:
    if: false
    continue-on-error: false
    needs:
      - test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        python-version: [ "3.10" ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-24.04'
        name: Install dependencies (ubuntu-24.04)
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          pip install tomte[tox]==0.6.5 tox-uv
          pip install --upgrade setuptools==60.10.0

          # install Protobuf compiler
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
          unzip protoc-3.11.4-linux-x86_64.zip -d protoc
          sudo mv protoc/bin/protoc /usr/local/bin/protoc

          # install IPFS
          sudo apt-get install -y wget
          wget -O ./go-ipfs.tar.gz https://dist.ipfs.io/go-ipfs/v0.6.0/go-ipfs_v0.6.0_linux-amd64.tar.gz
          tar xvfz go-ipfs.tar.gz
          sudo mv go-ipfs/ipfs /usr/local/bin/ipfs
          ipfs init

          # install Tendermint
          wget -O tendermint.tar.gz https://github.com/tendermint/tendermint/releases/download/v0.34.19/tendermint_0.34.19_linux_amd64.tar.gz
          tar -xf tendermint.tar.gz
          sudo mv tendermint /usr/local/bin/tendermint

          # pull node image needed for the integration tests
          docker pull node:16.7.0

      - name: e2e tests
        run: |
          tox -e py${{ matrix.python-version }}-linux -- -m 'e2e'